version: "3.8"

networks:
    pet_shop_api:
        driver: bridge

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        depends_on:
            - php
            - db
        ports:
            - "8084:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - pet_shop_api

    db:
        image: mysql:8.0.20
        container_name: db
        restart: unless-stopped
        tty: true
        networks:
            - pet_shop_api
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: pet_shop_api
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql

    php:
        container_name: php-pet_shop_api
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - pet_shop_api

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        container_name: phpmyadmin
        depends_on:
            - db
        ports:
            - "8085:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - pet_shop_api
