openapi: 3.0.0
# https://petstore3.swagger.io/api/v3/openapi.json
info:
  title: Pet Shop API - Swagger Documentation
  #  description: Pet Shop APIs.
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT

tags:
  - name: User
    description: User Api endpoint
  - name: Orders
    description: Orders Api endpoint
  - name: Categories
    description: List all categories
  - name: Products
    description: List all products

paths:
  /api/v1/user/login:
    post:
      tags:
        - User
      summary: Login an User account
      operationId: user-login
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  description: User email
                password:
                  type: string
                  description: User password
              type: object

      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        404:
          description: Page not found
        422:
          description: Unprocessable Entity
        500:
          description: Internal server error
      security: []

  /api/v1/user/create:
    post:
      tags:
        - User
      summary: Create a User account
      operationId: user-create
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - first_name
                - last_name
                - email
                - password
                - password_confirmation
                - address
                - phone_number
              properties:
                first_name:
                  type: string
                  description: User firstname
                last_name:
                  type: string
                  description: User lastname
                email:
                  type: string
                  description: User email
                password:
                  type: string
                  description: User password
                password_confirmation:
                  type: string
                  description: User password
                avatar:
                  type: string
                  description: Avatar image UUID
                address:
                  type: string
                  description: User main address
                phone_number:
                  type: string
                  description: User main phone number
                is_marketing:
                  type: string
                  description: User marketing preferences
              type: object

      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        404:
          description: Page not found
        422:
          description: Unprocessable Entity
        500:
          description: Internal server error
      security: []

  /api/v1/user/logout:
    get:
      tags:
        - User
      summary: Logout an User account
      operationId: user-logout
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        404:
          description: Page not found
        422:
          description: Unprocessable Entity
        500:
          description: Internal server error
      security:
        - bearerAuth: []

  /api/v1/categories:
    get:
      tags:
        - Categories
      summary: List all categories
      operationId: categories-listing
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        404:
          description: Page not found
        422:
          description: Unprocessable Entity
        500:
          description: Internal server error
      security: []

  /api/v1/category/{uuid}:
    get:
      tags:
        - Categories
      summary: Fetch a category
      operationId: categories-read
      parameters:
        - in: path
          name: uuid
          required: true
          schema:
            type: string

      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        404:
          description: Page not found
        422:
          description: Unprocessable Entity
        500:
          description: Internal server error
      security: []

  /api/v1/products:
    get:
      tags:
        - Products
      summary: List all products
      operationId: products-listing
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        404:
          description: Page not found
        422:
          description: Unprocessable Entity
        500:
          description: Internal server error
      security: []

  /api/v1/product/{uuid}:
    get:
      tags:
        - Products
      summary: Fetch a product,
      operationId: products-read
      parameters:
        - in: path
          name: uuid
          required: true
          schema:
            type: string

      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        404:
          description: Page not found
        422:
          description: Unprocessable Entity
        500:
          description: Internal server error
      security: []

  /api/v1/order/create:
    post:
      tags:
        - Orders
      summary: Create a new order
      operationId: orders-create
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - order_status_uuid
                - payment_uuid
                - products
                - address
              properties:
                order_status_uuid:
                  type: string
                  description: Order status UUID
                  example: 54599e11-70fb-4deb-83d9-9a33a04b0705
                payment_uuid:
                  type: string
                  description: Payment UUID
                  example: afb6c697-7ed3-4fe3-a7f4-615f21a576c1
                products:
                  type: array
                  items:
                    type: object
                    properties:
                      uuid:
                        type: string
                        description: Product UUID
                      quantity:
                        type: integer
                        description: Product quantity
                  description: Array of objects with product uuid and quantity. *swagger has a bug with arrays. Use postman for this endpoint.
                address:
                  type: object
                  properties:
                    billing:
                      type: string
                    shipping:
                      type: string
                  description: Billing and Shipping address
              type: object

      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        404:
          description: Page not found
        422:
          description: Unprocessable Entity
        500:
          description: Internal server error
      security:
        - bearerAuth: []
